In [1]:
import tensorflow as tf

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [ ]:
### Broadingcasting(广播机制)
    # 一种轻量级的张量复制手段，在逻辑上扩展张量数据的形状，但是只会在需要时才会执行实际存储复制操作（与tf.tile()区分）
    # 对于大部分场景,Broadingcasting机制都能通过优化手段避免实际复制数据而完成逻辑运算，从而相对于tf.tile函数，减少了大量计算代价

In [7]:
# 示例1：Broadingcasting机制都能通过优化手段避免实际复制数据而完成逻辑运算

In [8]:
x = tf.random.normal([2,4])
w = tf.random.normal([4,3])
b = tf.random.normal([3])
x@w+b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.5196582 , -0.44274753, -4.42363   ],
       [-0.6026311 , -0.18986443, -0.83654696]], dtype=float32)>

In [9]:
# 可以看到 x@w+b 并没有报错，这是因为它自动调用了Broadingcasting函数tf.broadcast_to(x,new_shape()),将两者shepe扩张为相同的[2，3]
# 如果手动扩展 可以将 x@w+b 改为 x@w+tf.broadcast(b,[2,3])

In [10]:
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.44949618, -0.50820726, -0.77487266], dtype=float32)>

In [ ]:
# b.shape is still [3].

In [ ]:
# 示例2：将[w,1] 扩展为 [b,h,w,c]
# 详细扩展示意
    #将w，1向右与w，c对齐，因为c为1，则可认为具有普适性，因此可以在逻辑上复制c-1份，将1变为c
    #对于空维度b，h，先自动插入新维度，新维度的长度为1，然后搞成b与h就行了
# 示例3：将[w,2] 扩展为 [b,h,w,c]
# 详细扩展示意
    #将w，1向右与w，c对齐，因为c为2，不具有普适性，无法应用Broadingcasting机制，将触发错误

In [5]:
# 创建矩阵
A = tf.random.normal([32,1]) 
# 扩展为 4D 张量
tf.broadcast_to(A, [2,32,32,3])

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.9311578 ,  0.9311578 ,  0.9311578 ],
         [ 0.8353306 ,  0.8353306 ,  0.8353306 ],
         [-1.828716  , -1.828716  , -1.828716  ],
         ...,
         [-2.399203  , -2.399203  , -2.399203  ],
         [-1.1711092 , -1.1711092 , -1.1711092 ],
         [ 0.37891454,  0.37891454,  0.37891454]],

        [[ 0.9311578 ,  0.9311578 ,  0.9311578 ],
         [ 0.8353306 ,  0.8353306 ,  0.8353306 ],
         [-1.828716  , -1.828716  , -1.828716  ],
         ...,
         [-2.399203  , -2.399203  , -2.399203  ],
         [-1.1711092 , -1.1711092 , -1.1711092 ],
         [ 0.37891454,  0.37891454,  0.37891454]],

        [[ 0.9311578 ,  0.9311578 ,  0.9311578 ],
         [ 0.8353306 ,  0.8353306 ,  0.8353306 ],
         [-1.828716  , -1.828716  , -1.828716  ],
         ...,
         [-2.399203  , -2.399203  , -2.399203  ],
         [-1.1711092 , -1.1711092 , -1.1711092 ],
         [ 0.37891454,  0.37891454,  0.37891454]

In [6]:
A = tf.random.normal([32,2])
# 不符合 Broadcasting 条件
try: 
    tf.broadcast_to(A, [2,32,32,4])
except Exception as e:
    print(e)

Incompatible shapes: [32,2] vs. [2,32,32,4] [Op:BroadcastTo]
