In [1]:
import tensorflow as tf

In [2]:
### 切片

In [ ]:
##1 start:end:step
    # start 开始读取位置的索引
    # end 结束读取位置的索引（不包含end位）
    # step 采样步长

In [ ]:
##2 start:end:step 的简写
    # 3个参数全部省略时为 :: 表示从开始读到末尾且步长为1（即不跳过任何元素）
        # 示例 x[0,::] 表示读取第一张图片的所有行，其中 :: 表示在行维度上读取所有行，等价于 x[0]    

In [8]:
##3 示例
# x[:,0:28:2,0:28:2,:]  (示例在下方)
# 表示 读取所有图片，隔行采样，隔列采样，读取所有通道数据

In [ ]:
##4 逆序
# start:end:-1 表示从start开始逆序读取至end结束（不包含end），索引号 end <= start  

In [9]:
# 考虑一个 0~9 的简单序列向量， 逆序取到第 1 号元素，不包含第 1 号
# 创建 0~9 向量
x = tf.range(9) 
# 从 8 取到 0，逆序，不包含 0
x[8:0:-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1])>

In [10]:
# 逆序全部元素
x[::-1] 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [11]:
# 逆序间隔采样
x[::-2] 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>

In [ ]:
##5 使用...避免冒号过多的情况（示例在下方）

In [3]:
# 创建4维张量（4张彩色图片）
x = tf.random.normal([4,32,32,3])

In [4]:
# 读取第 2,3 张图片
x[1:3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 9.41778958e-01, -5.40742278e-01,  2.18888476e-01],
         [-3.41377407e-01,  1.05937505e+00, -1.17684555e+00],
         [ 8.75150040e-02, -1.07762861e+00, -1.21890211e+00],
         ...,
         [ 6.80721343e-01,  5.14963627e-01, -3.94474149e-01],
         [ 9.22107816e-01,  1.27246618e+00, -1.03106022e+00],
         [-9.06378269e-01, -1.63964972e-01,  5.11904120e-01]],

        [[ 6.78550661e-01, -1.64132595e+00,  1.19988716e+00],
         [-1.19043767e+00, -1.04043819e-01, -8.97634447e-01],
         [ 1.68646252e+00,  2.21653447e-01, -6.23221934e-01],
         ...,
         [ 6.38689518e-01, -1.27553940e+00,  2.19595149e-01],
         [ 8.47007513e-01, -3.36342603e-01,  1.38488221e+00],
         [ 1.35362077e+00, -2.07726881e-01,  1.00858915e+00]],

        [[-1.91494083e+00, -9.71015394e-01, -4.23575014e-01],
         [ 6.50566280e-01, -2.49524087e-01, -3.67269307e-01],
         [-9.29053068e-01, -1.51734245e+00, 

In [5]:
# 读取第一张图片
x[0,::] 

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 1.16946865e-02,  1.16132951e+00,  2.27465600e-01],
        [ 9.01359260e-01,  4.64593768e-01, -6.32812306e-02],
        [-4.52238858e-01,  3.13985229e+00, -2.85805196e-01],
        ...,
        [ 2.33237475e-01, -1.98582208e+00,  2.95218170e-01],
        [ 3.40462387e-01, -4.44023043e-01, -1.74741066e+00],
        [-5.38810968e-01,  1.51886284e+00,  2.75503683e+00]],

       [[ 1.39167467e-02,  3.98869336e-01, -8.21433187e-01],
        [ 2.21513078e-01,  1.08448461e-01,  4.19087172e-01],
        [ 2.36873460e+00, -1.68940938e+00,  5.48868656e-01],
        ...,
        [ 1.16243351e+00,  8.84894669e-01,  5.10837018e-01],
        [-3.97987306e-01, -2.24646902e+00,  6.07664168e-01],
        [ 1.58227003e+00, -1.40780836e-01, -2.24950480e+00]],

       [[-4.21328992e-01, -4.77164149e-01, -1.01752174e+00],
        [ 6.71371669e-02,  9.28325504e-02, -2.85946220e-01],
        [ 4.34744209e-01,  1.07404685e+00,  4.61416692e-01],
  

In [7]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 1.16946865e-02,  1.16132951e+00,  2.27465600e-01],
         [-4.52238858e-01,  3.13985229e+00, -2.85805196e-01],
         [-9.83430743e-01,  3.16265881e-01,  4.55622554e-01],
         ...,
         [ 3.12522918e-01,  6.44492209e-01,  2.83037335e-01],
         [-2.94619977e-01, -8.12658906e-01,  5.28218091e-01],
         [ 3.88725877e-01, -1.13913774e+00,  2.91123480e-01]],

        [[-4.21328992e-01, -4.77164149e-01, -1.01752174e+00],
         [ 4.34744209e-01,  1.07404685e+00,  4.61416692e-01],
         [ 4.07211691e-01, -1.24176216e+00,  1.88668191e+00],
         ...,
         [-8.98564160e-01,  3.47860426e-01, -3.28940421e-01],
         [ 5.76505363e-01, -1.24103196e-01,  5.89605281e-03],
         [ 2.38042489e-01,  8.83617997e-01, -9.72727612e-02]],

        [[-6.15438104e-01,  8.88255179e-01,  1.64524503e-02],
         [-4.01555598e-01, -4.03213263e-01, -9.46495414e-01],
         [-3.11453372e-01,  1.05242364e-01, 

In [12]:
# 读取每张图片的所有通道，其中行按着逆序隔行采样，列按着逆序隔行采样

In [13]:
x = tf.random.normal([4,32,32,3])
# 行、列逆序间隔采样
x[0,::-2,::-2] 

<tf.Tensor: shape=(16, 16, 3), dtype=float32, numpy=
array([[[-1.7338976e+00, -9.5590454e-01,  1.4916226e+00],
        [ 1.6389284e-01,  2.3524959e-01, -4.3898386e-01],
        [ 4.2038986e-01, -5.0788093e-01,  4.1066823e-03],
        [-6.1967802e-01,  2.4412468e-01, -1.8833719e+00],
        [ 9.5529866e-01, -3.7493426e-01, -5.0654119e-01],
        [ 9.8361009e-01, -2.0510654e+00, -6.9804263e-01],
        [ 1.9422561e-01, -9.8519540e-01, -1.2630605e+00],
        [ 6.3520148e-02, -6.1183625e-01,  9.1301084e-01],
        [ 1.0306871e+00, -2.1279284e-01, -1.4357848e+00],
        [ 8.0621816e-02,  5.9828901e-01,  7.6129895e-01],
        [-6.3801163e-01,  8.1981611e-01, -2.6717153e+00],
        [-8.5469365e-01,  6.9963646e-01,  1.1458952e+00],
        [-4.8485532e-01, -3.6399347e-01, -1.0028198e+00],
        [ 5.6847703e-01, -3.5133007e-01, -9.0504646e-01],
        [-7.3857474e-01, -7.1390110e-01, -2.0404661e-01],
        [-2.2112767e-01, -1.0545539e+00,  8.4377068e-01]],

       [[ 1.64048

In [14]:
# 取 G 通道数据 
x[:,:,:,1] # 当张量的维度数量较多时，不需要采样的维度一般用单冒号:表示采样所有元素

<tf.Tensor: shape=(4, 32, 32), dtype=float32, numpy=
array([[[-1.1413331 , -1.631908  ,  0.3585765 , ..., -1.060952  ,
         -0.03147375, -0.81592155],
        [ 0.60494995, -1.2628318 , -2.5303938 , ..., -2.6018548 ,
         -0.58275497, -0.5827434 ],
        [-1.1369653 , -0.6034496 , -0.07648002, ...,  0.6691454 ,
         -0.42594832, -0.5019596 ],
        ...,
        [-1.005378  ,  1.2530419 ,  0.35439917, ...,  0.34767222,
         -1.366189  ,  0.36247587],
        [-1.566572  ,  1.6445599 ,  0.6972735 , ..., -1.3229556 ,
          0.6716637 ,  0.5751199 ],
        [-1.6278368 , -1.0545539 ,  0.9665916 , ...,  0.2352496 ,
         -0.6060832 , -0.95590454]],

       [[-1.0799172 ,  0.7445461 ,  0.45161557, ...,  0.7194175 ,
          0.4497127 ,  0.04740149],
        [-0.42939737, -0.02470366,  0.0394481 , ..., -0.6488565 ,
          1.2123322 ,  0.6087403 ],
        [ 0.3747244 , -1.019682  ,  1.2793957 , ...,  1.3128985 ,
          0.06164279,  1.4072635 ],
        ...,
 

In [15]:
# 读取最后 2 张图片
# 高、宽、通道维度全部采集，等价于 x[2:]
x[2:,...] 

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.2636385 ,  1.5818609 ,  0.3311409 ],
         [ 0.25124258, -0.484434  , -0.3843265 ],
         [ 0.07440352,  0.9296069 ,  1.4952626 ],
         ...,
         [ 0.19974405, -1.2209159 ,  0.61085427],
         [ 1.8505908 ,  0.681157  , -0.3552784 ],
         [ 1.2114514 , -1.0132046 , -1.1267874 ]],

        [[ 2.4040773 , -1.2375636 ,  0.21346712],
         [ 0.77282554, -0.55765253,  1.0719432 ],
         [ 0.10457737,  0.69778544,  0.76362675],
         ...,
         [-1.3509125 ,  0.255878  , -0.53347725],
         [ 0.09883873,  0.0140198 , -0.05539186],
         [ 0.64526916, -1.2068509 ,  0.20952116]],

        [[-0.48805887, -0.76234996, -1.5490208 ],
         [-0.65317154, -0.27198356, -1.0191325 ],
         [ 1.5841277 ,  1.1517814 , -0.01792271],
         ...,
         [ 0.7914919 , -0.57054347, -1.2288535 ],
         [-0.78819895, -0.67246276, -0.38019055],
         [ 2.3963406 ,  0.3737211 , -0.06939606]

In [16]:
# 读取所有样本，所有高、宽的前 2 个通道（R和G）的数据
x[...,:2] 

<tf.Tensor: shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[-0.34401762, -1.1413331 ],
         [ 1.96263   , -1.631908  ],
         [ 0.49059713,  0.3585765 ],
         ...,
         [ 1.0952039 , -1.060952  ],
         [ 1.3050473 , -0.03147375],
         [ 0.67056185, -0.81592155]],

        [[-0.18438417,  0.60494995],
         [-1.0723048 , -1.2628318 ],
         [ 0.7144213 , -2.5303938 ],
         ...,
         [-1.4531643 , -2.6018548 ],
         [ 0.90677977, -0.58275497],
         [-0.8436412 , -0.5827434 ]],

        [[-1.3522974 , -1.1369653 ],
         [-1.0427886 , -0.6034496 ],
         [ 0.02604572, -0.07648002],
         ...,
         [-0.13062364,  0.6691454 ],
         [-0.3245079 , -0.42594832],
         [-0.9986503 , -0.5019596 ]],

        ...,

        [[ 0.7261983 , -1.005378  ],
         [ 0.22293022,  1.2530419 ],
         [ 1.4348785 ,  0.35439917],
         ...,
         [-0.55839944,  0.34767222],
         [ 0.2670445 , -1.366189  ],
         [ 1.6404

In [17]:
# 读取第 1~2 张图片（所有高、宽的）后 2 个通道（G和B）的数据
x[0:2,...,1:] 

<tf.Tensor: shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[-1.1413331 ,  0.7666831 ],
         [-1.631908  ,  1.6296635 ],
         [ 0.3585765 , -0.9944804 ],
         ...,
         [-1.060952  ,  1.907731  ],
         [-0.03147375,  0.4380061 ],
         [-0.81592155, -0.39129227]],

        [[ 0.60494995,  0.81459016],
         [-1.2628318 ,  0.757506  ],
         [-2.5303938 , -0.6098743 ],
         ...,
         [-2.6018548 ,  0.5707513 ],
         [-0.58275497,  1.2862772 ],
         [-0.5827434 , -0.8081641 ]],

        [[-1.1369653 , -0.21142632],
         [-0.6034496 , -0.10506831],
         [-0.07648002, -0.82831913],
         ...,
         [ 0.6691454 , -0.63954264],
         [-0.42594832,  1.395355  ],
         [-0.5019596 , -0.39010313]],

        ...,

        [[-1.005378  , -0.9541285 ],
         [ 1.2530419 ,  0.19908468],
         [ 0.35439917, -0.09588417],
         ...,
         [ 0.34767222, -1.3879453 ],
         [-1.366189  ,  0.62105095],
         [ 0.3624