In [1]:
import tensorflow as tf

In [5]:
### 创建序列
    #tf.range(limit, delta=1)
    #tf.range(start,limit, delta=1)

In [ ]:
# tf.range(limit, delta=1)可以创建[0, limit)之间，步长为 delta 的整型序列，不包含 limit 本身。

In [2]:
# 创建0~10，步长为1的整形序列（不包含 10）
tf.range(10) 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [3]:
# 创建 0~10，步长为 2 的整形序列（不包含 10）
tf.range(10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [ ]:
# tf.range(start, limit, delta=1)可以创建[start, limit)之间，步长为 delta 的整型序列，不包含 limit 本身。

In [4]:
# 创建1~10，步长为2的整形序列（不包含 10）
tf.range(1,10,delta=2) 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>