In [9]:
import tensorflow as tf

In [ ]:
### 创建服从正态分布和均匀分的张量
    # tf.random.normal()
    # tf.random.uniform()

In [ ]:
# 通过 tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建形状为 shape，均值为mean，标准差为 stddev 的正态分布N(mean,stddev^2)

In [2]:
# 创建标准正态分布的张量（均值为0，标准差为1）
tf.random.normal([2,2]) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.74413747, -0.57561773],
       [ 0.35626298,  0.85224473]], dtype=float32)>

In [3]:
# 创建均值为 1，标准差为 2 的正态分布的张量
tf.random.normal([2,2], mean=1,stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.6175594 , -0.53798366],
       [-0.12657785,  1.4316336 ]], dtype=float32)>

In [4]:
# 通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自[minval, maxval)区间的均匀分布的张量

In [5]:
# 创建采样自[0,1)均匀分布的矩阵
tf.random.uniform([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.03627384, 0.17377663],
       [0.37421262, 0.8795078 ],
       [0.79032815, 0.5775318 ]], dtype=float32)>

In [6]:
# 创建采样自[0,10)均匀分布的矩阵
tf.random.uniform([2,2],maxval=10) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5.459299 , 5.4695215],
       [9.129274 , 9.013462 ]], dtype=float32)>

In [7]:
    #如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时指定数据类型为 tf.int*型

In [8]:
# 创建采样自[0,100)均匀分布的整型矩阵
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[92, 14],
       [86, 23]])>