In [6]:
import tensorflow as tf

In [11]:
###1 在创建张量时，可以指定张量的保存精度

In [12]:
# 常用的精度类型有tfint16,tf.int32,tf.int64,tf.float16,tf.float32,tf.float64(tf.double)等
# 位越长，精度越高，同时占用的内存空间也就越大

In [ ]:
# 创建int类型的标量

In [8]:
a = tf.constant(123456789, dtype=tf.int16)
a

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [10]:
# 可以看到，保存精度过低时，数据123456789发生了溢出，得到了错误的结果
# 所以，一般使用tf.int32,tf.int64精度

In [9]:
b = tf.constant(123456789, dtype=tf.int32)
b

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

In [13]:
# 创建flooat类型的标量

In [14]:
import numpy as np
# 从 numpy 中导入 pi 常量
np.pi 

3.141592653589793

In [17]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [18]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [19]:
# 可以看到，对于浮点数， 高精度的张量可以表示更精准的数据

In [20]:
###2 读取精度与精度转换

In [21]:
a = tf.constant(np.pi, dtype=tf.float16)

In [22]:
# 读取原有张量的数值精度
print('before:',a.dtype)

before: <dtype: 'float16'>


In [23]:
# 如果精度不符合要求，则进行转换
if a.dtype != tf.float32: 
    # tf.cast 函数可以完成精度转换
    a = tf.cast(a,tf.float32) 

In [25]:
# 打印转换后的精度
print('after :',a.dtype)

after : <dtype: 'float32'>


In [ ]:
# 进行类型转换时，需要保证转换操作的合法性， 例如将高精度的张量转换为低精度的张量时，可能发生数据溢出隐患：

In [26]:
a = tf.constant(123456789, dtype=tf.int32)
# 转换为低精度整型
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>