In [8]:
import tensorflow as tf

In [9]:
###1 如何使用tensorflow创建标量（0维张量）

In [10]:
a = 1.2

In [11]:
aa = tf.constant(1.2) # 如果要使用tf提供的功能函数，必须通过tf规定的方式去创建张量，而不能使用python语言的标准变量创建方式

In [12]:
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [13]:
###2 如何使用tensorflow创建向量（1维张量）

In [ ]:
# 与标量不同，向量的定义须通过 List 容器传给 tf.constant()函数。

In [14]:
x = tf.constant([1,2.,3.3])

In [15]:
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [ ]:
# 将 TF 张量的数据导出为 numpy 数组格式

In [16]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [17]:
# 创建一个元素的向量
a = tf.constant([1.2]) 

In [18]:
a.shape

TensorShape([1])

In [19]:
###3 如何使用tensorflow创建矩阵（2维张量）

In [20]:
# 创建 2 行 2 列的矩阵
a = tf.constant([[1,2],[3,4]]) 
a, a.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]))

In [21]:
###4 如何使用tensorflow创建3维张量

In [22]:
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [23]:
###5 如何使用tensorflow创建字符串

In [24]:
# 创建字符串
a = tf.constant('Hello, Deep Learning.') 
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

In [25]:
# 在 tf.strings 模块中，提供了常见的字符串类型的工具函数，如小写化 lower()、 拼接 join()、 长度 length()、 切分 split()等。

In [26]:
###6 如何使用tensorflow创建布尔类型

In [27]:
# # 创建布尔类型标量
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [28]:
 # 创建布尔类型向量
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [29]:
# 需要注意的是， TensorFlow 的布尔类型和 Python 语言的布尔类型并不等价，不能通用

In [30]:
# 创建 TF 布尔张量
a = tf.constant(True) 
# TF 布尔类型张量与 python 布尔类型比较
print(a is True) 

False


In [31]:
# 仅数值比较
print(a == True) 

tf.Tensor(True, shape=(), dtype=bool)
