In [2]:
import tensorflow as tf

In [3]:
### 标量的应用
    # 标量的一些典型用途是误差值的表示，各种测量指标的表示，如Accuracy,Precision,Recall etc.

In [4]:
# 示例：求平均均方差（标量）

In [5]:
# 随机模拟网络输出
    # 4x10 采样区间为[0,1)的均匀分布 
    # 4个样例，每个样例有10个属性
out = tf.random.uniform([4,10]) 
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.00440001, 0.26303828, 0.8563602 , 0.5043329 , 0.8863994 ,
        0.3594947 , 0.52962315, 0.02014339, 0.7715175 , 0.7418262 ],
       [0.51165354, 0.37398887, 0.85096085, 0.23830247, 0.88795376,
        0.53438294, 0.3917278 , 0.02296972, 0.23165679, 0.85793424],
       [0.3033675 , 0.27247965, 0.92978024, 0.13046777, 0.81294096,
        0.02179027, 0.26974535, 0.75264347, 0.77297544, 0.37631953],
       [0.35077214, 0.77806914, 0.8403939 , 0.31394625, 0.25867867,
        0.345515  , 0.8108183 , 0.05888331, 0.31872785, 0.5601127 ]],
      dtype=float32)>

In [6]:
# 随机构造样本真实标签
y = tf.constant([2,3,2,0]) # 4个样例所代表的类别标签
# one-hot 编码
y = tf.one_hot(y, depth=10)
y

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
# 计算每个样本的 MSE (均方差损失函数)
loss = tf.keras.losses.mse(y, out)
print(loss)

tf.Tensor([0.26855844 0.3723696  0.22279195 0.3094215 ], shape=(4,), dtype=float32)


In [8]:
# 平均 MSE,loss 应是标量
loss = tf.reduce_mean(loss) # 平均
print(loss)

tf.Tensor(0.29328537, shape=(), dtype=float32)


In [ ]:
### 向量的应用

In [ ]:
# 示例1：考虑 2 个输出节点的网络层， 创建长度为 2 的偏置向量b，并累加在每个输出节点上：

In [10]:
# z=wx,模拟获得激活函数的输入 z
z = tf.random.normal([4,2])
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-1.4462991 ,  0.03748394],
       [ 0.03203115, -0.1788525 ],
       [-0.42676398, -0.5305086 ],
       [ 0.9406645 , -1.3922616 ]], dtype=float32)>

In [16]:
# 创建偏置向量
b = tf.zeros([2])
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [17]:
# 累加上偏置向量
z = z + b 
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.44629908,  1.0374839 ],
       [ 1.0320312 ,  0.8211475 ],
       [ 0.573236  ,  0.46949142],
       [ 1.9406645 , -0.39226162]], dtype=float32)>

In [21]:
# 示例2：创建输入节点数为 4，输出节点数为 3 的线性层网络，那么它的偏置向量 b 的长度应为 3

In [22]:
# 创建一层 Wx+b，输出节点为 3
fc = tf.keras.layers.Dense(3)
print(fc)

In [23]:
# 通过 build 函数创建 W,b 张量，输入节点为 4
fc.build(input_shape=(2,4))

In [24]:
# 查看偏置向量
fc.bias 

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [25]:
### 矩阵的应用

In [ ]:
# 示例1

In [26]:
# 2 个样本，特征长度为 4 的张量
x = tf.random.normal([2,4]) 
# 定义 W 张量
w = tf.ones([4,3])
# 定义 b 张量
b = tf.zeros([3]) 
# X@W+b 运算
o = x@w+b 
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.270505 ,  4.270505 ,  4.270505 ],
       [-0.8736721, -0.8736721, -0.8736721]], dtype=float32)>

In [ ]:
# 示例2

In [27]:
# 定义全连接层的输出节点为 3
fc = tf.keras.layers.Dense(3) 
# 定义全连接层的输入节点为 4
fc.build(input_shape=(2,4)) 
# 查看权值矩阵 W
fc.kernel 

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.47602892,  0.47631538,  0.3989967 ],
       [-0.04306078, -0.3699699 ,  0.41760516],
       [ 0.5270711 , -0.44457114,  0.5008323 ],
       [-0.7398998 ,  0.40547383,  0.05295223]], dtype=float32)>

In [ ]:
### 三维张量

In [29]:
import tensorflow.keras as keras
# 自动加载 IMDB 电影评价数据集
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)
# 将句子填充、截断为等长 80 个单词的句子
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)
x_train.shape

17473536/17464789 [==============================] - 7s 0us/step


(25000, 80)

In [31]:
x_train

array([[  15,  256,    4, ...,   19,  178,   32],
       [ 125,   68,    2, ...,   16,  145,   95],
       [ 645,  662,    8, ...,    7,  129,  113],
       ...,
       [ 529,  443,    2, ...,    4, 3586,    2],
       [ 286, 1814,   23, ...,   12,    9,   23],
       [  97,   90,   35, ...,  204,  131,    9]])

In [ ]:
# 可以看到 x_train 张量的 shape 为[25000,80]，其中 25000 表示句子个数， 80 表示每个句子共 80 个单词，每个单词使用数字编码方式表示。

In [ ]:
# 通过 layers.Embedding 层将数字编码的单词转换为长度为 100 个词向量：

In [32]:
# 创建词向量 Embedding 层类
embedding = tf.keras.layers.Embedding(10000, 100)
# 将数字编码的单词转换为词向量
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

In [34]:
out[0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.031038668>

In [ ]:
# 可以看到，经过 Embedding 层编码后，句子张量的 shape 变为[25000,80,100]，其中 100 表示每个单词编码为长度是 100 的向量。

In [35]:
### 四维张量

In [37]:
import tensorflow.keras.layers as layers
# 创建 32x32 的彩色图片输入，个数为 4
x = tf.random.normal([4,32,32,3])
# 创建卷积神经网络
layer = layers.Conv2D(16, kernel_size=3)
# 前向计算
out = layer(x) 
# 输出大小
out.shape

TensorShape([4, 30, 30, 16])

In [38]:
# 访问卷积核张量
layer.kernel.shape 

TensorShape([3, 3, 3, 16])