In [2]:
import tensorflow as tf

In [23]:
### 数学运算
    #加减乘除
    #整除
    #除余
    #乘方
    #平方与平方根
    #指数
    #自然指数
    #对数运算与换底公式
    #矩阵相乘

In [ ]:
##1.8 矩阵相乘
    #A与B能够相乘的条件
        #A的倒数第一个维度长度和B的倒数第二个维度长度必须相等
    #相乘运算符
        #@
        #tf.matmul(a,b)
    #Tensorflow中的矩阵相乘可以使用批量方式，即张量A与B的维度数可以大于2
        #当张量A与B的维度数大于2时，tf会选择A和B的最后两个维度进行矩阵相乘，前面所有的维度都视为Batch维度
    #tf.matmul(a,b)支持自动Broadcasting机制

In [ ]:
## 1.1 最基本的加减乘除运算直接使用+ - * /

In [5]:
b = tf.constant(2)
c =tf.constant(3)
b/c

<tf.Tensor: shape=(), dtype=float64, numpy=0.6666666666666666>

In [6]:
##1.2 整除 //

In [8]:
a = tf.range(5)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [9]:
b = tf.constant(2)
a//b 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [10]:
##1.3 除余 %

In [11]:
a%b 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

In [13]:
##1.4 乘方运算（2种不同的形式）

In [14]:
#1.4.1
x = tf.range(4)
tf.pow(x,3) 

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [15]:
#1.4.2
x**2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9])>

In [ ]:
##1.5 平方与平方根（2种不同的形式）运算

In [16]:
x=tf.constant([1.,4.,9.])
# 平方根
x**(0.5)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [18]:
x = tf.range(5)
# 转换为浮点数
x = tf.cast(x, dtype=tf.float32) 
# 平方
x = tf.square(x) 
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [19]:
# 平方根
tf.sqrt(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [ ]:
##1.6 指数运算

In [20]:
x = tf.constant([1.,2.,3.])
# 指数运算
2**x 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [21]:
##1.7 自然指数运算

In [22]:
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [ ]:
##1.8 对数运算

In [24]:
x = tf.exp(3.)
# 对数运算
tf.math.log(x) 

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [26]:
x = tf.constant([1.,2.])
x = 10**x
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.     , 99.99999], dtype=float32)>

In [27]:
# 换底公式
tf.math.log(x)/tf.math.log(10.) 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [28]:
##1.8 矩阵相乘

In [29]:
a = tf.random.normal([4,3,28,32])
b = tf.random.normal([4,3,32,2])
# 批量形式的矩阵相乘
a@b

<tf.Tensor: shape=(4, 3, 28, 2), dtype=float32, numpy=
array([[[[ 5.91158926e-01,  2.76742864e+00],
         [ 4.21930885e+00,  5.04911566e+00],
         [-7.37570715e+00,  6.35024977e+00],
         [-2.64738888e-01,  5.83055210e+00],
         [ 5.00786161e+00,  1.16156697e+00],
         [ 1.91615796e+00, -6.07799864e+00],
         [-6.75090265e+00,  8.42743015e+00],
         [ 3.22096539e+00,  8.37116718e+00],
         [-2.16981983e+00, -8.85271454e+00],
         [ 1.53742707e+00, -1.83755815e+00],
         [ 1.39636555e+01,  1.03044856e+00],
         [ 1.25161266e+01, -1.00102558e+01],
         [ 6.97458565e-01,  5.03255785e-01],
         [ 4.84751731e-01, -2.18899921e-02],
         [ 9.10590231e-01, -1.04935923e+01],
         [ 2.70345341e-02, -9.91388440e-01],
         [ 3.60485029e+00, -5.18003988e+00],
         [-1.04688015e+01,  8.91376877e+00],
         [ 8.27964687e+00,  5.11640406e+00],
         [-3.60110760e+00,  9.84555721e+00],
         [-4.71546030e+00, -6.88653612e+00],


In [30]:
a = tf.random.normal([4,28,32])
b = tf.random.normal([32,16])
# 先自动扩展，再矩阵相乘
tf.matmul(a,b)

<tf.Tensor: shape=(4, 28, 16), dtype=float32, numpy=
array([[[  0.34285313,   9.024972  ,  -0.5513944 , ...,  -0.32624146,
         -17.80771   ,   0.28201243],
        [  6.448079  ,   0.20534983,  -1.7190651 , ...,   6.030036  ,
          -3.7538984 ,   2.2149267 ],
        [  2.152541  ,   2.9980288 ,  -5.888814  , ...,  -1.9303815 ,
          -5.2092957 ,   4.2169304 ],
        ...,
        [  4.8497715 ,   4.459289  ,  10.183895  , ...,  -0.5108822 ,
         -16.902317  ,  -5.5754952 ],
        [  3.1999063 ,   1.7598726 , -10.663238  , ...,   4.201476  ,
          -4.4216547 ,  -1.2801867 ],
        [  1.6567905 ,  -2.2655277 ,  14.377407  , ...,  -1.4048455 ,
          -3.8604238 ,   2.51867   ]],

       [[-12.250758  ,  -4.6476483 ,   1.2342222 , ...,  -6.890478  ,
           6.486438  ,  -2.5829594 ],
        [ -5.3774667 ,  -1.7984258 ,  -2.2861764 , ...,   1.0382608 ,
          -0.33539698,  -3.7933524 ],
        [  2.3651643 ,   0.43049943,  11.804843  , ...,  -5.31306   

In [ ]:
# 可以看到，b被自动扩展为公共shape[4,32,16],再与a进行批量形式的矩阵相乘，得到的结果为[4,28,16]