In [1]:
import tensorflow as tf

In [2]:
### 索引

In [3]:
# 创建4维张量（4张彩色图片）
x = tf.random.normal([4,32,32,3])

In [4]:
# 取第 1 张图片的数据
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.18027598,  0.9540487 , -0.4593162 ],
        [ 0.47916305, -1.0379349 ,  0.80905306],
        [-1.0495822 ,  0.88050073,  0.08185571],
        ...,
        [ 0.8192562 , -0.3520053 , -2.1027572 ],
        [ 2.449665  , -1.4130754 ,  2.2820776 ],
        [ 0.4887177 ,  1.3125634 , -0.02116959]],

       [[ 0.7492407 , -0.2715708 ,  0.37467617],
        [ 0.83842736,  0.34928247,  0.34488165],
        [-0.8613825 , -0.35168755,  0.5603118 ],
        ...,
        [ 1.3735404 ,  0.27020192,  0.5576199 ],
        [ 1.3300408 , -0.02496228,  0.88533413],
        [ 2.246438  ,  0.8167357 , -0.3437823 ]],

       [[-1.6759372 , -1.3732558 ,  1.9001026 ],
        [-2.5563045 ,  1.2326422 ,  1.3919244 ],
        [-0.48795074, -1.24595   ,  0.6591501 ],
        ...,
        [ 0.7079578 , -1.6652666 ,  1.6656109 ],
        [-0.14659573,  1.182277  ,  0.6110125 ],
        [-0.22247958, -0.17453763,  1.1493992 ]],

       ...,

       

In [5]:
# 取第 1 张图片的第 2 行
x[0][1]

<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
array([[ 0.7492407 , -0.2715708 ,  0.37467617],
       [ 0.83842736,  0.34928247,  0.34488165],
       [-0.8613825 , -0.35168755,  0.5603118 ],
       [ 0.7629353 , -1.1331805 ,  0.3304656 ],
       [-0.72146505,  2.1595342 , -0.12128511],
       [-0.4034748 , -2.248676  , -0.17080255],
       [ 0.54077923, -1.2068259 ,  0.19820638],
       [-0.98951596,  1.2108873 ,  1.167212  ],
       [ 1.0170045 ,  0.5619506 , -0.92357826],
       [-0.18719867,  0.21374671,  0.15017891],
       [ 0.4616921 ,  0.399425  ,  2.114249  ],
       [-0.51299465,  1.4896525 , -0.64868456],
       [ 0.44814542, -0.8273785 ,  0.98001397],
       [-0.62752324,  0.45318514,  0.8247997 ],
       [ 0.42954078,  1.3751421 , -0.3173129 ],
       [ 0.07558331,  1.1941308 , -1.2221116 ],
       [ 0.7600544 , -1.7406693 , -0.6171176 ],
       [-0.48116165,  0.86197746,  1.5537226 ],
       [ 0.37632024,  0.4584467 ,  1.1252471 ],
       [ 0.33324116,  1.6663679 , -0.70

In [6]:
# 取第 1 张图片，第 2 行，第 3 列的数据
x[0][1][2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.8613825 , -0.35168755,  0.5603118 ], dtype=float32)>

In [7]:
# 取第 3 张图片，第 2 行，第 1 列的像素， B 通道(第 2 个通道)颜色强度值
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.93156004>