In [2]:
import tensorflow as tf

In [3]:
### 维度变换

In [4]:
##1 维度变换的功能是什么？
# 算法的每个模块对于数据张量的格式有不同的逻辑要求，当现有的数据格式不满足算法要求时，
# 需要通过维度变换将数据调整为正确的格式。

In [5]:
# 示例 y = wx + b 
# w为2x4 x为4x3 wx为2x3 而b定义为[3] 
# 此时就需要运用矩阵变换（复制）将 b = [b1,b2,b3] 变成 b = [[b1,b2,b3] [b1,b2,b3]] 
# 这样做不仅满足数学上矩阵相加所需要的条件，同时也实现了给每个输入样本的输出节点共享偏置向量的逻辑

In [6]:
##2 基本的维度变换操作函数
    # 改变视图reshape
    # 插入新维度expand_dims
    # 删除维度squeeze
    # 交换维度transpose （tf.reshape() 与 tf.transpose()的区别）
    # 复制数据tile
# 注意：增加只能增加长度为1的维度，删除也只能删除长度为1的维度

In [7]:
##2.1 改变视图

In [8]:
# 张量的两个概念：存储与视图
    # 视图：理解张量的方式 
    # 存储：张量在内存上保存为一段连续的内存区域
# 存储与视图的关系
    # 举例说明 A.shape 为 [2,4,4,3] 
    # 在不改变张量的存储下，可以有以下2中理解方式（视图）：
        # 2张图片，每张图片4行4列，每个位置有RGB 3个通道的数据
        # 2个样本，每个样本的特征为长度48的向量
    # 总结：同一个存储，从不同的角度观察数据，可以产生不同的视图

In [9]:
#2.1.1 将1维张量转换为4维张量

In [10]:
# 生成向量
x = tf.range(96) 
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])>

In [11]:
# 改变 x 的视图，获得 4D 张量，存储并未改变
x = tf.reshape(x,[2,4,4,3]) 
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [12]:
# 可以看到，数据顺序仍是0~95，可见数据并未改变，改变的是数据结构

In [13]:
#2.1.2 获取张量的维度数和形状列表
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [14]:
#2.1.3 通过 tf.reshape(x, new_shape)，可以将张量的视图任意地合法改变

In [15]:
b = tf.reshape(x,[2,-1]) # 参数-1表示当前轴上长度需要根据张量总元素不变的法则自动推导
b

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [16]:
tf.reshape(b,[2,4,-1])

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [17]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]])>

In [18]:
## 2.2 增加维度

In [27]:
# 产生矩阵
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[4, 7, 7, 4, 8, 9, 3, 4, 5, 0, 8, 2, 3, 3, 9, 1, 7, 1, 8, 8, 7, 6,
        3, 8, 1, 7, 4, 9],
       [7, 4, 0, 0, 1, 0, 0, 4, 0, 5, 0, 7, 7, 0, 3, 2, 6, 0, 8, 7, 6, 1,
        3, 4, 0, 0, 5, 0],
       [1, 7, 9, 2, 0, 3, 5, 0, 5, 1, 7, 9, 5, 0, 1, 0, 6, 2, 7, 7, 9, 6,
        7, 0, 7, 9, 2, 7],
       [0, 7, 9, 4, 7, 1, 8, 3, 4, 1, 3, 3, 0, 7, 5, 6, 3, 1, 3, 5, 5, 8,
        4, 7, 8, 7, 4, 2],
       [8, 5, 3, 2, 4, 7, 4, 5, 4, 3, 1, 1, 0, 7, 4, 9, 6, 9, 3, 1, 7, 7,
        4, 6, 2, 2, 7, 9],
       [3, 1, 9, 2, 1, 2, 3, 1, 0, 7, 1, 4, 9, 3, 3, 3, 9, 7, 6, 1, 6, 9,
        0, 1, 9, 5, 0, 4],
       [1, 0, 7, 2, 0, 0, 8, 2, 9, 1, 6, 9, 5, 7, 7, 4, 5, 5, 2, 5, 3, 2,
        6, 3, 1, 0, 5, 0],
       [2, 8, 9, 6, 2, 8, 0, 5, 8, 0, 8, 4, 9, 7, 9, 7, 0, 2, 5, 9, 9, 5,
        3, 8, 5, 8, 3, 5],
       [6, 5, 4, 8, 4, 5, 0, 6, 0, 7, 7, 5, 0, 7, 4, 8, 4, 5, 8, 3, 0, 9,
        7, 1, 5, 7, 3, 0],
       [5, 3, 7, 0, 9, 3, 1, 4, 4, 8, 9, 4,

In [28]:
# 通过 tf.expand_dims(x, axis)可在指定的 axis 轴前可以插入一个新的维度
    # axis为正时，表示在当前维度之前插入一个新维度
    # axis为负时，表示在当前维度之后插入一个新的维度
        # 假设x有4维(1, 28, 28, 1)，从左到右的索引分别为1，2，3，4 与 -4，-3，-2，-1 

In [29]:
# axis=2 表示宽维度后面的一个维度
x = tf.expand_dims(x,axis=2) 
x

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[4],
        [7],
        [7],
        [4],
        [8],
        [9],
        [3],
        [4],
        [5],
        [0],
        [8],
        [2],
        [3],
        [3],
        [9],
        [1],
        [7],
        [1],
        [8],
        [8],
        [7],
        [6],
        [3],
        [8],
        [1],
        [7],
        [4],
        [9]],

       [[7],
        [4],
        [0],
        [0],
        [1],
        [0],
        [0],
        [4],
        [0],
        [5],
        [0],
        [7],
        [7],
        [0],
        [3],
        [2],
        [6],
        [0],
        [8],
        [7],
        [6],
        [1],
        [3],
        [4],
        [0],
        [0],
        [5],
        [0]],

       [[1],
        [7],
        [9],
        [2],
        [0],
        [3],
        [5],
        [0],
        [5],
        [1],
        [7],
        [9],
        [5],
        [0],
        [1],
        [0],
        [

In [30]:
# 可以看到，插入一个新维度后，数据的存储顺序并没有改变，仅仅是改变了数据的视图

In [31]:
x = tf.expand_dims(x,axis=0) # 高维度之前插入新维度
x

<tf.Tensor: shape=(1, 28, 28, 1), dtype=int32, numpy=
array([[[[4],
         [7],
         [7],
         [4],
         [8],
         [9],
         [3],
         [4],
         [5],
         [0],
         [8],
         [2],
         [3],
         [3],
         [9],
         [1],
         [7],
         [1],
         [8],
         [8],
         [7],
         [6],
         [3],
         [8],
         [1],
         [7],
         [4],
         [9]],

        [[7],
         [4],
         [0],
         [0],
         [1],
         [0],
         [0],
         [4],
         [0],
         [5],
         [0],
         [7],
         [7],
         [0],
         [3],
         [2],
         [6],
         [0],
         [8],
         [7],
         [6],
         [1],
         [3],
         [4],
         [0],
         [0],
         [5],
         [0]],

        [[1],
         [7],
         [9],
         [2],
         [0],
         [3],
         [5],
         [0],
         [5],
         [1],
         [7],
    

In [32]:
x = tf.expand_dims(x,axis=-3) # axis为负时 
x

<tf.Tensor: shape=(1, 28, 1, 28, 1), dtype=int32, numpy=
array([[[[[4],
          [7],
          [7],
          [4],
          [8],
          [9],
          [3],
          [4],
          [5],
          [0],
          [8],
          [2],
          [3],
          [3],
          [9],
          [1],
          [7],
          [1],
          [8],
          [8],
          [7],
          [6],
          [3],
          [8],
          [1],
          [7],
          [4],
          [9]]],


        [[[7],
          [4],
          [0],
          [0],
          [1],
          [0],
          [0],
          [4],
          [0],
          [5],
          [0],
          [7],
          [7],
          [0],
          [3],
          [2],
          [6],
          [0],
          [8],
          [7],
          [6],
          [1],
          [3],
          [4],
          [0],
          [0],
          [5],
          [0]]],


        [[[1],
          [7],
          [9],
          [2],
          [0],
          [3],
     

In [33]:
##2.3 删除维度

In [34]:
x = tf.squeeze(x, axis=0) # 删除图片数量维度
x

<tf.Tensor: shape=(28, 1, 28, 1), dtype=int32, numpy=
array([[[[4],
         [7],
         [7],
         [4],
         [8],
         [9],
         [3],
         [4],
         [5],
         [0],
         [8],
         [2],
         [3],
         [3],
         [9],
         [1],
         [7],
         [1],
         [8],
         [8],
         [7],
         [6],
         [3],
         [8],
         [1],
         [7],
         [4],
         [9]]],


       [[[7],
         [4],
         [0],
         [0],
         [1],
         [0],
         [0],
         [4],
         [0],
         [5],
         [0],
         [7],
         [7],
         [0],
         [3],
         [2],
         [6],
         [0],
         [8],
         [7],
         [6],
         [1],
         [3],
         [4],
         [0],
         [0],
         [5],
         [0]]],


       [[[1],
         [7],
         [9],
         [2],
         [0],
         [3],
         [5],
         [0],
         [5],
         [1],
         [7],


In [35]:
x = tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)
tf.squeeze(x) # 如果不指定维度参数axis，将会删除所有长度为 1 的维度  

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[8, 0, 0, 0, 3, 1, 5, 7, 2, 6, 7, 3, 6, 4, 8, 0, 9, 1, 0, 0, 7, 5,
        8, 9, 4, 0, 8, 5],
       [2, 9, 3, 8, 3, 0, 7, 2, 1, 7, 8, 2, 9, 7, 1, 8, 0, 4, 9, 3, 7, 1,
        1, 4, 9, 5, 8, 1],
       [0, 6, 8, 8, 6, 0, 8, 2, 0, 4, 6, 4, 7, 1, 8, 1, 9, 8, 5, 1, 5, 1,
        6, 5, 7, 8, 9, 9],
       [8, 6, 4, 1, 6, 8, 0, 0, 4, 3, 1, 8, 9, 1, 1, 6, 1, 7, 8, 2, 7, 8,
        3, 2, 8, 1, 6, 0],
       [3, 7, 1, 0, 0, 8, 6, 3, 9, 3, 8, 2, 0, 4, 1, 9, 3, 7, 6, 9, 6, 2,
        1, 3, 9, 4, 5, 2],
       [2, 6, 4, 5, 8, 5, 6, 9, 8, 8, 2, 3, 4, 4, 3, 6, 5, 0, 6, 9, 0, 9,
        4, 1, 1, 0, 2, 7],
       [2, 8, 1, 5, 9, 0, 0, 3, 5, 4, 4, 0, 4, 4, 8, 7, 4, 0, 4, 2, 2, 0,
        6, 6, 3, 2, 5, 8],
       [5, 3, 9, 1, 0, 1, 0, 0, 5, 3, 9, 2, 3, 9, 0, 2, 9, 9, 5, 9, 7, 3,
        9, 1, 3, 7, 5, 5],
       [0, 0, 7, 4, 1, 3, 2, 3, 2, 3, 8, 6, 6, 7, 7, 7, 3, 9, 5, 8, 8, 0,
        3, 7, 6, 4, 9, 8],
       [1, 2, 3, 6, 2, 4, 8, 2, 5, 8, 1, 5,

In [36]:
##2.4 交换维度

In [38]:
# tf.reshape() 与 tf.transpose()的区别
    # tf.reshape() 仅改变张量的视图
    # tf.transpose() 既改变张量的视图，同时也改变张量的存储顺序

In [ ]:
# 示例 [b,h,w,c] 转换为 [b,c,h,w]

In [37]:
x = tf.random.normal([2,32,32,3])
# 交换维度
tf.transpose(x,perm=[0,3,1,2])

<tf.Tensor: shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 0.8295612 ,  0.6780858 ,  0.8446382 , ..., -1.1265782 ,
          -0.51109385, -0.80859077],
         [-1.3348218 , -0.11567135, -0.8434625 , ...,  0.36834106,
           1.0768609 , -0.45127842],
         [ 0.4164837 ,  0.43307757,  0.57402307, ..., -0.3720446 ,
          -0.24548687,  1.0056041 ],
         ...,
         [ 0.9295488 ,  0.2841511 ,  1.0799018 , ..., -1.1165262 ,
           0.35248455,  1.1652339 ],
         [-1.0915979 , -0.06294353, -0.00539165, ...,  0.40927464,
          -0.582915  , -0.14558405],
         [ 0.30707547,  1.4244809 ,  0.12891053, ..., -1.5090955 ,
           0.9255735 ,  0.25433126]],

        [[-1.1194268 , -0.08562431, -1.1607898 , ...,  0.11251407,
          -1.5550457 , -0.9664672 ],
         [-1.6525542 , -0.07410085,  0.21191783, ..., -0.20946454,
           0.38580838,  0.18658856],
         [ 0.76650625, -0.38693693, -0.42709762, ..., -1.3296523 ,
          -0.29391354,  0.362

In [42]:
## 2.5 复制数据

In [ ]:
# 2.5.1 示例1：将[1,2]转换成[[1, 2],
#                           [1, 2]]

In [41]:
# 创建向量 b
b = tf.constant([1,2]) 
# 插入新维度，变成矩阵
b = tf.expand_dims(b, axis=0) 
# 样本维度上复制一份
b = tf.tile(b, multiples=[2,1])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]])>

In [43]:
# 2.5.2 示例2：矩阵的列复制与行复制

In [44]:
x = tf.range(4)
# 创建 2 行 2 列矩阵
x=tf.reshape(x,[2,2]) 
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [45]:
# 列维度复制一份
x = tf.tile(x,multiples=[1,2]) 
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [46]:
# 行维度复制一份
x = tf.tile(x,multiples=[2,1]) 
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>